services:
  backend:
    image: adamtuska/jobtracker-backend:latest
    container_name: jobtracker-backend

    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - Jwt__Key=${JWT_KEY}
      - Authentication__Google__ClientId=${Authentication__Google__ClientId}
      - Authentication__Google__ClientSecret=${Authentication__Google__ClientSecret}

    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - ix-postgres_default
      
networks:
  ix-postgres_default:
    external: true
